// The design-sync library entry: what Claude Design imports as window.TibbieX.
// src/ui/ is the design system (content-blind, props-only); the brand glyphs
// and the Reagan Youth mark come from src/assets/. MagicDust (a global canvas
// mounted once by App) and Honeypot (an invisible bot trap) are left out.
// A new src/ui/ component needs a line here to reach the sync.
export { default as PatreonIcon } from "../src/assets/icons/PatreonIcon"
export { default as TikTokIcon } from "../src/assets/icons/TikTokIcon"
export { default as VenmoIcon } from "../src/assets/icons/VenmoIcon"
export { default as ReaganYouthMark } from "../src/assets/marks/ReaganYouthMark"
export { default as AlbumTile } from "../src/ui/cards/AlbumTile"
export { default as PhotoGrid } from "../src/ui/cards/PhotoGrid"
export { default as PolaroidStack } from "../src/ui/cards/PolaroidStack"
export { default as PriceCard } from "../src/ui/cards/PriceCard"
export { default as ShopCard } from "../src/ui/cards/ShopCard"
export { default as ShopLink } from "../src/ui/cards/ShopLink"
export { default as Button } from "../src/ui/controls/Button"
export { default as Chip } from "../src/ui/controls/Chip"
export { default as EmailField } from "../src/ui/controls/EmailField"
export { default as Field } from "../src/ui/controls/Field"
export { default as FilterPill } from "../src/ui/controls/FilterPill"
export { default as SocialButton } from "../src/ui/controls/SocialButton"
export { default as TabItem } from "../src/ui/controls/TabItem"
export { default as TextArea } from "../src/ui/controls/TextArea"
export { default as VenmoLink } from "../src/ui/controls/VenmoLink"
export { default as Avatar } from "../src/ui/display/Avatar"
export { default as DetailList } from "../src/ui/display/DetailList"
export { default as Meter } from "../src/ui/display/Meter"
export { default as PanelHeader } from "../src/ui/display/PanelHeader"
export { default as Pill } from "../src/ui/display/Pill"
export { default as Separator } from "../src/ui/display/Separator"
export { default as SiteQrCode } from "../src/ui/display/SiteQrCode"
export { default as Lightbox } from "../src/ui/overlays/Lightbox"
export { default as Overlay } from "../src/ui/overlays/Overlay"
export { default as OverlayBody } from "../src/ui/overlays/OverlayBody"
export { default as LinkRow } from "../src/ui/rows/LinkRow"
export { default as ShowRow } from "../src/ui/rows/ShowRow"
export { default as SupporterRow } from "../src/ui/rows/SupporterRow"
